apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-deploy-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: build-deploy-trigger
      interceptors:
        - name: "CEL filter: only master brancher pushed"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/master']"
      bindings:
        - ref: build-deploy-binding
      template:
        ref: build-deploy-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: build-deploy-binding
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: image-name
      value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-deploy-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
    - name: image-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-deploy-trigger-run-
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: build-mvn-jib
        params:
          - name: image-url
            value: 966958450174.dkr.ecr.ap-northeast-2.amazonaws.com/$(tt.params.image-name)
          - name: revision
            value: $(tt.params.gitrevision)
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: insecure-registry
            value: "false"
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: pvc-build
        - name: gitops
          emptyDir: {}
