apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
  - name: argo-app-name
  - name: gitops-url
    default: "http://gitea.m2mcx01-public/tekton/m2mcx01-demo-deploy.git"
  - name: gitops-revision
    default: "kust"
  - name: image-url
  - name: build-id
  - name: deploy-manifest
    default: "kustomization.yaml"
  - name: argo-url
    default: "argocd-server.argocd:443"

  workspaces:
  - name: gitops

  stepTemplate:
    envFrom:
    - secretRef:
        name: argocd-env-secret
    env:
    - name: ARGOCD_SERVER
      value: $(params.argo-url)

  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.gitops.path)"
    script: |
      #!/usr/bin/env sh
      git init
      git remote add origin $(params.gitops-url)
      git fetch --depth 1 origin $(params.gitops-revision)
      git checkout $(params.gitops-revision)
  - name: update-yaml
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.gitops.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      echo "updating image to $(inputs.params.image-url):$(inputs.params.build-id)"
      sed -i "s|newTag:.*$|newTag: $(params.build-id)|" dev/$(params.deploy-manifest)
  - name: commit-push-changes-gitops
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.gitops.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      git config --global user.email "tekton@tekton.dev"
      git config --global user.name "Tekton Pipeline"
      git add .
      git commit --allow-empty -m "[tekton] updating image to $(inputs.params.build-id)"
      git push origin $(params.gitops-revision)
  - name: wait-for-argocd-rollout
    image: quay.io/argoproj/argocd:v2.4.8
    script: |
      #!/usr/bin/env sh
      #set -e
      argocd app sync $(inputs.params.argo-app-name) --insecure
      exit 0
      #argocd app wait $(inputs.params.argo-app-name) --sync --health --operation --insecure

