apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: argo-deploy-
spec:
  serviceAccountName: sa-pipeline-runner
  params:
  - name: argo-app-name
    value: "m2mcx01-demo-kust-dev"
  - name: gitops-url
    value: "http://gitea.m2mcx01-public/tekton/m2mcx01-demo-deploy.git"
  - name: image-url
    value: "966958450174.dkr.ecr.ap-northeast-2.amazonaws.com/m2mcx01-demo"
  - name: build-id
    value: "v5"
  taskRef:
    name: deploy
    kind: Task
  workspaces:
    - name: gitops
      emptyDir: {}
